overrides:
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  esbuild@<=0.24.2: '>=0.25.0'
  cookie@<0.7.0: '>=0.7.0'
  undici@<5.29.0: '>=5.29.0'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  "path-to-regexp": "8.0.0"
