// Currency code to name mapping
export const CURRENCY_NAMES: Record<string, string> = {
  // Fiat currencies
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  SEK: "Swedish Krona",
  NZD: "New Zealand Dollar",
  MXN: "Mexican Peso",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  NOK: "Norwegian Krone",
  KRW: "South Korean Won",
  TRY: "Turkish Lira",
  RUB: "Russian Ruble",
  INR: "Indian Rupee",
  BRL: "Brazilian Real",
  ZAR: "South African Rand",
  PHP: "Philippine Peso",
  CZK: "Czech Koruna",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  HUF: "Hungarian Forint",
  ISK: "Icelandic Krona",
  HRK: "Croatian Kuna",
  BGN: "Bulgarian Lev",
  RON: "Romanian Leu",
  DKK: "Danish Krone",
  THB: "Thai Baht",
  PLN: "Polish Zloty",
  ILS: "Israeli Shekel",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  ARS: "Argentine Peso",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  VND: "Vietnamese Dong",
  PKR: "Pakistani Rupee",
  EGP: "Egyptian Pound",
  NGN: "Nigerian Naira",
  KES: "Kenyan Shilling",
  GHS: "Ghanaian Cedi",
  MAD: "Moroccan Dirham",
  TZS: "Tanzanian Shilling",
  UGX: "Ugandan Shilling",

  // Cryptocurrencies
  BTC: "Bitcoin",
  ETH: "Ethereum",
  USDT: "Tether",
  USDC: "USD Coin",
  BNB: "Binance Coin",
  XRP: "Ripple",
  ADA: "Cardano",
  SOL: "Solana",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  MATIC: "Polygon",
  LTC: "Litecoin",
  AVAX: "Avalanche",
  UNI: "Uniswap",
  LINK: "Chainlink",
  ATOM: "Cosmos",
  XLM: "Stellar",
  BCH: "Bitcoin Cash",
  ALGO: "Algorand",
  VET: "VeChain",
  FIL: "Filecoin",
  TRX: "TRON",
  DAI: "Dai",
  ETC: "Ethereum Classic",
  XMR: "Monero",
  XTZ: "Tezos",
  AAVE: "Aave",
  MKR: "Maker",
  SAND: "The Sandbox",
  MANA: "Decentraland",
}

export function getCurrencyName(code: string): string {
  return CURRENCY_NAMES[code] || code
}
